// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: service/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolAPI_Login_FullMethodName              = "/api.PoolAPI/Login"
	PoolAPI_Logout_FullMethodName             = "/api.PoolAPI/Logout"
	PoolAPI_KeepAlive_FullMethodName          = "/api.PoolAPI/KeepAlive"
	PoolAPI_List_FullMethodName               = "/api.PoolAPI/List"
	PoolAPI_Stat_FullMethodName               = "/api.PoolAPI/Stat"
	PoolAPI_ExistsDir_FullMethodName          = "/api.PoolAPI/ExistsDir"
	PoolAPI_ExistsFile_FullMethodName         = "/api.PoolAPI/ExistsFile"
	PoolAPI_RemoveFile_FullMethodName         = "/api.PoolAPI/RemoveFile"
	PoolAPI_RemoveDir_FullMethodName          = "/api.PoolAPI/RemoveDir"
	PoolAPI_MakeDir_FullMethodName            = "/api.PoolAPI/MakeDir"
	PoolAPI_RenameDirToDir_FullMethodName     = "/api.PoolAPI/RenameDirToDir"
	PoolAPI_RenameFileToFile_FullMethodName   = "/api.PoolAPI/RenameFileToFile"
	PoolAPI_CreateFile_FullMethodName         = "/api.PoolAPI/CreateFile"
	PoolAPI_OpenFile_FullMethodName           = "/api.PoolAPI/OpenFile"
	PoolAPI_TruncateFile_FullMethodName       = "/api.PoolAPI/TruncateFile"
	PoolAPI_ReadAt_FullMethodName             = "/api.PoolAPI/ReadAt"
	PoolAPI_WriteAt_FullMethodName            = "/api.PoolAPI/WriteAt"
	PoolAPI_GetAvailable_FullMethodName       = "/api.PoolAPI/GetAvailable"
	PoolAPI_Truncate_FullMethodName           = "/api.PoolAPI/Truncate"
	PoolAPI_Flush_FullMethodName              = "/api.PoolAPI/Flush"
	PoolAPI_Close_FullMethodName              = "/api.PoolAPI/Close"
	PoolAPI_ReadStream_FullMethodName         = "/api.PoolAPI/ReadStream"
	PoolAPI_ReadStreamParallel_FullMethodName = "/api.PoolAPI/ReadStreamParallel"
	PoolAPI_WriteStream_FullMethodName        = "/api.PoolAPI/WriteStream"
	PoolAPI_CacheFile_FullMethodName          = "/api.PoolAPI/CacheFile"
	PoolAPI_Sync_FullMethodName               = "/api.PoolAPI/Sync"
)

// PoolAPIClient is the client API for PoolAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoolAPIClient interface {
	// Session
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*Empty, error)
	// Filesystem
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ExistsDir(ctx context.Context, in *ExistsDirRequest, opts ...grpc.CallOption) (*ExistsDirResponse, error)
	ExistsFile(ctx context.Context, in *ExistsFileRequest, opts ...grpc.CallOption) (*ExistsFileResponse, error)
	RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveDir(ctx context.Context, in *RemoveDirRequest, opts ...grpc.CallOption) (*Empty, error)
	MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*Empty, error)
	RenameDirToDir(ctx context.Context, in *RenameDirToDirRequest, opts ...grpc.CallOption) (*Empty, error)
	RenameFileToFile(ctx context.Context, in *RenameFileToFileRequest, opts ...grpc.CallOption) (*Empty, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error)
	TruncateFile(ctx context.Context, in *TruncateFileRequest, opts ...grpc.CallOption) (*Empty, error)
	// File handle (RDWR pass-through)
	ReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (*ReadAtResponse, error)
	WriteAt(ctx context.Context, in *WriteAtRequest, opts ...grpc.CallOption) (*WriteAtResponse, error)
	GetAvailable(ctx context.Context, in *GetAvailableRequest, opts ...grpc.CallOption) (*GetAvailableResponse, error)
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*Empty, error)
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*Empty, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Empty, error)
	// File handle streaming (RDONLY - server streams 4MB blocks for prefetch)
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadStreamResponse], error)
	// File streaming (RDONLY - server reads in parallel and streams blocks)
	ReadStreamParallel(ctx context.Context, in *ReadStreamParallelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadStreamParallelResponse], error)
	// File handle streaming (WRONLY - client streams micro-buffered chunks)
	WriteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteStreamRequest, WriteStreamResponse], error)
	// Cache
	CacheFile(ctx context.Context, in *CacheFileRequest, opts ...grpc.CallOption) (*Empty, error)
	// Sync
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*Empty, error)
}

type poolAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolAPIClient(cc grpc.ClientConnInterface) PoolAPIClient {
	return &poolAPIClient{cc}
}

func (c *poolAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, PoolAPI_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_KeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, PoolAPI_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, PoolAPI_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) ExistsDir(ctx context.Context, in *ExistsDirRequest, opts ...grpc.CallOption) (*ExistsDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsDirResponse)
	err := c.cc.Invoke(ctx, PoolAPI_ExistsDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) ExistsFile(ctx context.Context, in *ExistsFileRequest, opts ...grpc.CallOption) (*ExistsFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsFileResponse)
	err := c.cc.Invoke(ctx, PoolAPI_ExistsFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) RemoveDir(ctx context.Context, in *RemoveDirRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_RemoveDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_MakeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) RenameDirToDir(ctx context.Context, in *RenameDirToDirRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_RenameDirToDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) RenameFileToFile(ctx context.Context, in *RenameFileToFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_RenameFileToFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, PoolAPI_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenFileResponse)
	err := c.cc.Invoke(ctx, PoolAPI_OpenFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) TruncateFile(ctx context.Context, in *TruncateFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_TruncateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) ReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (*ReadAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAtResponse)
	err := c.cc.Invoke(ctx, PoolAPI_ReadAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) WriteAt(ctx context.Context, in *WriteAtRequest, opts ...grpc.CallOption) (*WriteAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAtResponse)
	err := c.cc.Invoke(ctx, PoolAPI_WriteAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) GetAvailable(ctx context.Context, in *GetAvailableRequest, opts ...grpc.CallOption) (*GetAvailableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableResponse)
	err := c.cc.Invoke(ctx, PoolAPI_GetAvailable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_Truncate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolAPI_ServiceDesc.Streams[0], PoolAPI_ReadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadStreamRequest, ReadStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolAPI_ReadStreamClient = grpc.ServerStreamingClient[ReadStreamResponse]

func (c *poolAPIClient) ReadStreamParallel(ctx context.Context, in *ReadStreamParallelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadStreamParallelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolAPI_ServiceDesc.Streams[1], PoolAPI_ReadStreamParallel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadStreamParallelRequest, ReadStreamParallelResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolAPI_ReadStreamParallelClient = grpc.ServerStreamingClient[ReadStreamParallelResponse]

func (c *poolAPIClient) WriteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteStreamRequest, WriteStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PoolAPI_ServiceDesc.Streams[2], PoolAPI_WriteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteStreamRequest, WriteStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolAPI_WriteStreamClient = grpc.ClientStreamingClient[WriteStreamRequest, WriteStreamResponse]

func (c *poolAPIClient) CacheFile(ctx context.Context, in *CacheFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_CacheFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAPIClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PoolAPI_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolAPIServer is the server API for PoolAPI service.
// All implementations must embed UnimplementedPoolAPIServer
// for forward compatibility.
type PoolAPIServer interface {
	// Session
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*Empty, error)
	KeepAlive(context.Context, *KeepAliveRequest) (*Empty, error)
	// Filesystem
	List(context.Context, *ListRequest) (*ListResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	ExistsDir(context.Context, *ExistsDirRequest) (*ExistsDirResponse, error)
	ExistsFile(context.Context, *ExistsFileRequest) (*ExistsFileResponse, error)
	RemoveFile(context.Context, *RemoveFileRequest) (*Empty, error)
	RemoveDir(context.Context, *RemoveDirRequest) (*Empty, error)
	MakeDir(context.Context, *MakeDirRequest) (*Empty, error)
	RenameDirToDir(context.Context, *RenameDirToDirRequest) (*Empty, error)
	RenameFileToFile(context.Context, *RenameFileToFileRequest) (*Empty, error)
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	OpenFile(context.Context, *OpenFileRequest) (*OpenFileResponse, error)
	TruncateFile(context.Context, *TruncateFileRequest) (*Empty, error)
	// File handle (RDWR pass-through)
	ReadAt(context.Context, *ReadAtRequest) (*ReadAtResponse, error)
	WriteAt(context.Context, *WriteAtRequest) (*WriteAtResponse, error)
	GetAvailable(context.Context, *GetAvailableRequest) (*GetAvailableResponse, error)
	Truncate(context.Context, *TruncateRequest) (*Empty, error)
	Flush(context.Context, *FlushRequest) (*Empty, error)
	Close(context.Context, *CloseRequest) (*Empty, error)
	// File handle streaming (RDONLY - server streams 4MB blocks for prefetch)
	ReadStream(*ReadStreamRequest, grpc.ServerStreamingServer[ReadStreamResponse]) error
	// File streaming (RDONLY - server reads in parallel and streams blocks)
	ReadStreamParallel(*ReadStreamParallelRequest, grpc.ServerStreamingServer[ReadStreamParallelResponse]) error
	// File handle streaming (WRONLY - client streams micro-buffered chunks)
	WriteStream(grpc.ClientStreamingServer[WriteStreamRequest, WriteStreamResponse]) error
	// Cache
	CacheFile(context.Context, *CacheFileRequest) (*Empty, error)
	// Sync
	Sync(context.Context, *SyncRequest) (*Empty, error)
	mustEmbedUnimplementedPoolAPIServer()
}

// UnimplementedPoolAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolAPIServer struct{}

func (UnimplementedPoolAPIServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPoolAPIServer) Logout(context.Context, *LogoutRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedPoolAPIServer) KeepAlive(context.Context, *KeepAliveRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedPoolAPIServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPoolAPIServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedPoolAPIServer) ExistsDir(context.Context, *ExistsDirRequest) (*ExistsDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistsDir not implemented")
}
func (UnimplementedPoolAPIServer) ExistsFile(context.Context, *ExistsFileRequest) (*ExistsFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistsFile not implemented")
}
func (UnimplementedPoolAPIServer) RemoveFile(context.Context, *RemoveFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedPoolAPIServer) RemoveDir(context.Context, *RemoveDirRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDir not implemented")
}
func (UnimplementedPoolAPIServer) MakeDir(context.Context, *MakeDirRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeDir not implemented")
}
func (UnimplementedPoolAPIServer) RenameDirToDir(context.Context, *RenameDirToDirRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameDirToDir not implemented")
}
func (UnimplementedPoolAPIServer) RenameFileToFile(context.Context, *RenameFileToFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFileToFile not implemented")
}
func (UnimplementedPoolAPIServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedPoolAPIServer) OpenFile(context.Context, *OpenFileRequest) (*OpenFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenFile not implemented")
}
func (UnimplementedPoolAPIServer) TruncateFile(context.Context, *TruncateFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TruncateFile not implemented")
}
func (UnimplementedPoolAPIServer) ReadAt(context.Context, *ReadAtRequest) (*ReadAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAt not implemented")
}
func (UnimplementedPoolAPIServer) WriteAt(context.Context, *WriteAtRequest) (*WriteAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAt not implemented")
}
func (UnimplementedPoolAPIServer) GetAvailable(context.Context, *GetAvailableRequest) (*GetAvailableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailable not implemented")
}
func (UnimplementedPoolAPIServer) Truncate(context.Context, *TruncateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Truncate not implemented")
}
func (UnimplementedPoolAPIServer) Flush(context.Context, *FlushRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedPoolAPIServer) Close(context.Context, *CloseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedPoolAPIServer) ReadStream(*ReadStreamRequest, grpc.ServerStreamingServer[ReadStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadStream not implemented")
}
func (UnimplementedPoolAPIServer) ReadStreamParallel(*ReadStreamParallelRequest, grpc.ServerStreamingServer[ReadStreamParallelResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadStreamParallel not implemented")
}
func (UnimplementedPoolAPIServer) WriteStream(grpc.ClientStreamingServer[WriteStreamRequest, WriteStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteStream not implemented")
}
func (UnimplementedPoolAPIServer) CacheFile(context.Context, *CacheFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheFile not implemented")
}
func (UnimplementedPoolAPIServer) Sync(context.Context, *SyncRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedPoolAPIServer) mustEmbedUnimplementedPoolAPIServer() {}
func (UnimplementedPoolAPIServer) testEmbeddedByValue()                 {}

// UnsafePoolAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolAPIServer will
// result in compilation errors.
type UnsafePoolAPIServer interface {
	mustEmbedUnimplementedPoolAPIServer()
}

func RegisterPoolAPIServer(s grpc.ServiceRegistrar, srv PoolAPIServer) {
	// If the following call panics, it indicates UnimplementedPoolAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolAPI_ServiceDesc, srv)
}

func _PoolAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_KeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_ExistsDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).ExistsDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_ExistsDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).ExistsDir(ctx, req.(*ExistsDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_ExistsFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).ExistsFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_ExistsFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).ExistsFile(ctx, req.(*ExistsFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).RemoveFile(ctx, req.(*RemoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_RemoveDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).RemoveDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_RemoveDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).RemoveDir(ctx, req.(*RemoveDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_MakeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).MakeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_MakeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).MakeDir(ctx, req.(*MakeDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_RenameDirToDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameDirToDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).RenameDirToDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_RenameDirToDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).RenameDirToDir(ctx, req.(*RenameDirToDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_RenameFileToFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileToFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).RenameFileToFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_RenameFileToFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).RenameFileToFile(ctx, req.(*RenameFileToFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_OpenFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).OpenFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_OpenFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).OpenFile(ctx, req.(*OpenFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_TruncateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).TruncateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_TruncateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).TruncateFile(ctx, req.(*TruncateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_ReadAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).ReadAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_ReadAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).ReadAt(ctx, req.(*ReadAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_WriteAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).WriteAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_WriteAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).WriteAt(ctx, req.(*WriteAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_GetAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).GetAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_GetAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).GetAvailable(ctx, req.(*GetAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Truncate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Truncate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Truncate(ctx, req.(*TruncateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_ReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolAPIServer).ReadStream(m, &grpc.GenericServerStream[ReadStreamRequest, ReadStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolAPI_ReadStreamServer = grpc.ServerStreamingServer[ReadStreamResponse]

func _PoolAPI_ReadStreamParallel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamParallelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PoolAPIServer).ReadStreamParallel(m, &grpc.GenericServerStream[ReadStreamParallelRequest, ReadStreamParallelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolAPI_ReadStreamParallelServer = grpc.ServerStreamingServer[ReadStreamParallelResponse]

func _PoolAPI_WriteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoolAPIServer).WriteStream(&grpc.GenericServerStream[WriteStreamRequest, WriteStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PoolAPI_WriteStreamServer = grpc.ClientStreamingServer[WriteStreamRequest, WriteStreamResponse]

func _PoolAPI_CacheFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).CacheFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_CacheFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).CacheFile(ctx, req.(*CacheFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAPI_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAPIServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAPI_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAPIServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolAPI_ServiceDesc is the grpc.ServiceDesc for PoolAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.PoolAPI",
	HandlerType: (*PoolAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _PoolAPI_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PoolAPI_Logout_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _PoolAPI_KeepAlive_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PoolAPI_List_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _PoolAPI_Stat_Handler,
		},
		{
			MethodName: "ExistsDir",
			Handler:    _PoolAPI_ExistsDir_Handler,
		},
		{
			MethodName: "ExistsFile",
			Handler:    _PoolAPI_ExistsFile_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _PoolAPI_RemoveFile_Handler,
		},
		{
			MethodName: "RemoveDir",
			Handler:    _PoolAPI_RemoveDir_Handler,
		},
		{
			MethodName: "MakeDir",
			Handler:    _PoolAPI_MakeDir_Handler,
		},
		{
			MethodName: "RenameDirToDir",
			Handler:    _PoolAPI_RenameDirToDir_Handler,
		},
		{
			MethodName: "RenameFileToFile",
			Handler:    _PoolAPI_RenameFileToFile_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _PoolAPI_CreateFile_Handler,
		},
		{
			MethodName: "OpenFile",
			Handler:    _PoolAPI_OpenFile_Handler,
		},
		{
			MethodName: "TruncateFile",
			Handler:    _PoolAPI_TruncateFile_Handler,
		},
		{
			MethodName: "ReadAt",
			Handler:    _PoolAPI_ReadAt_Handler,
		},
		{
			MethodName: "WriteAt",
			Handler:    _PoolAPI_WriteAt_Handler,
		},
		{
			MethodName: "GetAvailable",
			Handler:    _PoolAPI_GetAvailable_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _PoolAPI_Truncate_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _PoolAPI_Flush_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _PoolAPI_Close_Handler,
		},
		{
			MethodName: "CacheFile",
			Handler:    _PoolAPI_CacheFile_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _PoolAPI_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadStream",
			Handler:       _PoolAPI_ReadStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadStreamParallel",
			Handler:       _PoolAPI_ReadStreamParallel_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteStream",
			Handler:       _PoolAPI_WriteStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service/api/api.proto",
}
